num_epochs: 300

#model_name: tf_efficientnetv2_m
#batch_size: 32

#model_name: resnet18
#batch_size: 64

#model_name: &model_name swin_base_patch4_window12_384
model_name: &model_name resnet18
batch_size: &batch_size 16
image_size: 224

#model_name: &model_name swin_base_patch4_window7_224
#batch_size: &batch_size 64

root_folder: data/coco/towers
image_folder: ${root_folder}/images/cropped
annotation_file: ${root_folder}/annotations
annotations:
  train: ${annotation_folder}/instances_train_5066.json
  valid: ${annotation_folder}/instances_valid_0599.json

logdir: logs
checkpoint_dir: ${logdir}/checkpoints

data:
  num_classes:
    _target_: commons.classification.multihead.get_num_classes
    annotations: ${annotations[train]}
    category_id: ${category_id}
    attribute_ids: ${attribute_ids}

loaders:
  train:
    _target_: torch.utils.data.DataLoader
    dataset:
      _target_: dataset.CroppedTowerDataset
      image_folder: ${image_folder}
      annotation_filename: ${annotations[train]}
      mode: train
      category_id: ${category_id}
      attribute_ids: ${attribute_ids}
      transforms:
        _target_: transforms.get_transforms
        mode: train
        image_size: ${image_size}
    batch_size: ${batch_size}
  valid:
    _target_: torch.utils.data.DataLoader
    dataset:
      _target_: dataset.CroppedTowerDataset
      image_folder: ${image_folder}
      annotation_filename: ${annotations[valid]}
      mode: valid
      category_id: ${category_id}
      attribute_ids: ${attribute_ids}
      transforms:
        _target_: transforms.get_transforms
        mode: valid
        image_size: ${image_size}
    batch_size: ${batch_size}

model:
  _target_: commons.classification.multihead.MultiheadModel
  model_name: ${model_name}
  num_classes: ${data[num_classes]}

criterion:
  _target_: torch.nn.CrossEntropyLoss

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0001

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.7

